version: '3'

networks:
  monitor:
    driver: bridge

services:
  flask-service:
    build: ./flask-service
    ports:
      - 8000:8000
      - 9000:9000
    networks:
      - monitor
  
  prometheus:
    build: ./prometheus
  
    networks:
      - monitor
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:5.2.1
    networks: 
      - monitor
    ports:
      - 3000:3000
